groups:
  kinect:
    operating_mode: position
    profile_type: time
    profile_velocity: 2000
    profile_acceleration: 300
    torque_enable: true

port: /dev/ttyDXL

joint_order: [pan,]
sleep_positions: [0,]

joint_state_publisher:
  update_rate: 100
  publish_states: true
  topic_name: joint_states
